# Use official Node.js runtime as base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Define build arguments
ARG NEXT_PUBLIC_DEV
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_SMTP_HOST
ARG NEXT_PUBLIC_SMTP_PORT
ARG NEXT_PUBLIC_SMTP_USER
ARG NEXT_PUBLIC_SMTP_PASSWORD
ARG NEXT_PUBLIC_SMTP_FROM_EMAIL

# Set environment variables from build arguments
ENV NEXT_PUBLIC_DEV=$NEXT_PUBLIC_DEV
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_SMTP_HOST=$NEXT_PUBLIC_SMTP_HOST
ENV NEXT_PUBLIC_SMTP_PORT=$NEXT_PUBLIC_SMTP_PORT
ENV NEXT_PUBLIC_SMTP_USER=$NEXT_PUBLIC_SMTP_USER
ENV NEXT_PUBLIC_SMTP_PASSWORD=$NEXT_PUBLIC_SMTP_PASSWORD
ENV NEXT_PUBLIC_SMTP_FROM_EMAIL=$NEXT_PUBLIC_SMTP_FROM_EMAIL

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Expose port
EXPOSE 3000

# Define environment variable
ENV NODE_ENV=production

# Start the application
CMD ["npm", "start"]
