name: Deploy to Kubesa

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Kubesa
        run: |
          echo "Triggering deployment..."          
          curl -X POST https://kubernetes-deployment-platform-main.52bda5.app.isacitra.com/api/v1/deployments/git \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "dd517b7a-53f6-4038-a9c6-803a15e1abe9",
              "apiKey": "${{ secrets.KUBESA_API_KEY }}",
              "commitId": "${{ github.sha }}",
              "commitMessage": "${{ github.event.head_commit.message }}"
            }'
          
          echo "Deployment initiated. Check deployment status and logs in the Kubesa web interface."
